# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Category.delete_all
Category.create([
  {name: 'formal'},
  {name: 'casual'}
])
## Each entry seperated by brackets, all entries must be followed by comma
## except for the last.
Pair.delete_all
Pair.create([
  { headline_font: 'Pompiere',
    body_font: 'Flamenco',
    category_id: Category.where(name: 'formal').first.id,
    slider1: 1,
    slider2: 1,
    slider3: 1
  },
  { headline_font: 'Shadows Into Light Two',
    body_font: 'Raleway',
    category_id: Category.where(name: 'casual').first.id,
    slider1: 1,
    slider2: 1,
    slider3: 1
  },
  { headline_font: 'Quando',
    body_font: 'Varela Round',
    category_id: Category.where(name: 'casual').first.id,
    slider1: 1,
    slider2: 3,
    slider3: 2
  },
  { headline_font: 'Quando',
    body_font: 'Rosario',
    category_id: Category.where(name: 'casual').first.id,
    slider1: 3,
    slider2: 3,
    slider3: 4
  },
  { headline_font: 'Quando',
    body_font: 'Fauna One',
    category_id: Category.where(name: 'casual').first.id,
    slider1: 2,
    slider2: 2,
    slider3: 4
  },
  { headline_font: 'Quando',
    body_font: 'Arimo',
    category_id: Category.where(name: 'casual').first.id,
    slider1: 3,
    slider2: 3,
    slider3: 3
  },
  { headline_font: 'Quando',
    body_font: 'Cabin',
    category_id: Category.where(name: 'casual').first.id,
    slider1: 3,
    slider2: 3,
    slider3: 3
  },
  { headline_font: 'Lemon',
    body_font: 'Josefin Sans',
    category_id: Category.where(name: 'casual').first.id,
    slider1: 2,
    slider2: 3,
    slider3: 2
  },
  { headline_font: 'Lemon',
    body_font: 'Muli',
    category_id: Category.where(name: 'casual').first.id,
    slider1: 2,
    slider2: 4,
    slider3: 3
  },
  { headline_font: 'Lemon',
    body_font: 'Roboto',
    category_id: Category.where(name: 'casual').first.id,
    slider1: 3,
    slider2: 4,
    slider3: 3
  },
  { headline_font: 'Lemon',
    body_font: 'PT Sans',
    category_id: Category.where(name: 'casual').first.id,
    slider1: 2,
    slider2: 4,
    slider3: 3
  },
  { headline_font: 'Lemon',
    body_font: 'Ubuntu',
    category_id: Category.where(name: 'casual').first.id,
    slider1: 2,
    slider2: 4,
    slider3: 2
  },
  { headline_font: 'Bowlby One',
    body_font: 'Alef',
    category_id: Category.where(name: 'casual').first.id,
    slider1: 4,
    slider2: 5,
    slider3: 2
  },
  { headline_font: 'Bowlby One',
    body_font: 'Open Sans',
    category_id: Category.where(name: 'casual').first.id,
    slider1: 3,
    slider2: 5,
    slider3: 2
  },
  { headline_font: 'Bowlby One',
    body_font: 'PT Sans',
    category_id: Category.where(name: 'casual').first.id,
    slider1: 4,
    slider2: 5,
    slider3: 2
  },
  { headline_font: 'Bowlby One',
    body_font: 'Chivo',
    category_id: Category.where(name: 'casual').first.id,
    slider1: 4,
    slider2: 5,
    slider3: 2
  },
  { headline_font: 'Bowlby One',
    body_font: 'Istok Web',
    category_id: Category.where(name: 'casual').first.id,
    slider1: 3,
    slider2: 5,
    slider3: 2
  },
  { headline_font: 'Lily Script One',
    body_font: 'Josefin Sans',
    category_id: Category.where(name: 'casual').first.id,
    slider1: 2,
    slider2: 3,
    slider3: 3
  },
  { headline_font: 'Lily Script One',
    body_font: 'Kite One',
    category_id: Category.where(name: 'casual').first.id,
    slider1: 1,
    slider2: 4,
    slider3: 4
  },
  { headline_font: 'Lily Script One',
    body_font: 'Oranienbaum',
    category_id: Category.where(name: 'casual').first.id,
    slider1: 2,
    slider2: 4,
    slider3: 3
  },
  { headline_font: 'Lily Script One',
    body_font: 'Overlock',
    category_id: Category.where(name: 'casual').first.id,
    slider1: 2,
    slider2: 4,
    slider3: 2
  },
  { headline_font: 'Lily Script One',
    body_font: 'Ruluko',
    category_id: Category.where(name: 'casual').first.id,
    slider1: 2,
    slider2: 4,
    slider3: 3
  },
  { headline_font: 'Montserrat',
    body_font: 'Balthazar',
    category_id: Category.where(name: 'formal').first.id,
    slider1: 5,
    slider2: 3,
    slider3: 3
  },
  { headline_font: 'Montserrat',
    body_font: 'Droid Sans',
    category_id: Category.where(name: 'formal').first.id,
    slider1: 4,
    slider2: 3,
    slider3: 2
  },
  { headline_font: 'Montserrat',
    body_font: 'Voces',
    category_id: Category.where(name: 'formal').first.id,
    slider1: 4,
    slider2: 3,
    slider3: 2
  },
  { headline_font: 'Montserrat',
    body_font: 'Scada',
    category_id: Category.where(name: 'formal').first.id,
    slider1: 4,
    slider2: 3,
    slider3: 3
  },
  { headline_font: 'Montserrat',
    body_font: 'Actor',
    category_id: Category.where(name: 'formal').first.id,
    slider1: 3,
    slider2: 3,
    slider3: 2
  },
  { headline_font: 'Archivo Black',
    body_font: 'Lato',
    category_id: Category.where(name: 'formal').first.id,
    slider1: 4,
    slider2: 5,
    slider3: 2
  },
  { headline_font: 'Archivo Black',
    body_font: 'Open Sans',
    category_id: Category.where(name: 'formal').first.id,
    slider1: 3,
    slider2: 4,
    slider3: 2
  },
  { headline_font: 'Archivo Black',
    body_font: 'Roboto',
    category_id: Category.where(name: 'formal').first.id,
    slider1: 3,
    slider2: 4,
    slider3: 2
  },
  { headline_font: 'Archivo Black',
    body_font: 'Source Sans Pro',
    category_id: Category.where(name: 'formal').first.id,
    slider1: 3,
    slider2: 4,
    slider3: 3
  },
  { headline_font: 'Archivo Black',
    body_font: 'Raleway',
    category_id: Category.where(name: 'formal').first.id,
    slider1: 2,
    slider2: 3,
    slider3: 1
  },
  { headline_font: 'Gravitas One',
    body_font: 'Lato',
    category_id: Category.where(name: 'formal').first.id,
    slider1: 3,
    slider2: 5,
    slider3: 3
  },
  { headline_font: 'Gravitas One',
    body_font: 'Prata',
    category_id: Category.where(name: 'formal').first.id,
    slider1: 2,
    slider2: 5,
    slider3: 5
  },
  { headline_font: 'Gravitas One',
    body_font: 'Tienne',
    category_id: Category.where(name: 'formal').first.id,
    slider1: 3,
    slider2: 5,
    slider3: 4
  },
  { headline_font: 'Gravitas One',
    body_font: 'Unna',
    category_id: Category.where(name: 'formal').first.id,
    slider1: 4,
    slider2: 5,
    slider3: 4
  },
  { headline_font: 'Gravitas One',
    body_font: 'Vollkorn',
    category_id: Category.where(name: 'formal').first.id,
    slider1: 3,
    slider2: 5,
    slider3: 5
  },
  { headline_font: 'Bree Serif',
    body_font: 'Josefin Sans',
    category_id: Category.where(name: 'casual').first.id,
    slider1: 3,
    slider2: 2,
    slider3: 2
  },
  { headline_font: 'Bree Serif',
    body_font: 'Istok Web',
    category_id: Category.where(name: 'casual').first.id,
    slider1: 4,
    slider2: 3,
    slider3: 3
  },
  { headline_font: 'Bree Serif',
    body_font: 'Convergence',
    category_id: Category.where(name: 'casual').first.id,
    slider1: 2,
    slider2: 4,
    slider3: 3
  },
  { headline_font: 'Bree Serif',
    body_font: 'Didact Gothic',
    category_id: Category.where(name: 'casual').first.id,
    slider1: 2,
    slider2: 3,
    slider3: 4
  },
  { headline_font: 'Bree Serif',
    body_font: 'Source Sans Pro',
    category_id: Category.where(name: 'casual').first.id,
    slider1: 3,
    slider2: 3,
    slider3: 3
  },
  { headline_font: 'Hammersmith One',
    body_font: 'Raleway',
    category_id: Category.where(name: 'casual').first.id,
    slider1: 2,
    slider2: 3,
    slider3: 1
  },
  { headline_font: 'Hammersmith One',
    body_font: 'Roboto',
    category_id: Category.where(name: 'casual').first.id,
    slider1: 4,
    slider2: 4,
    slider3: 2
  },
  { headline_font: 'Hammersmith One',
    body_font: 'Lato',
    category_id: Category.where(name: 'casual').first.id,
    slider1: 4,
    slider2: 4,
    slider3: 2
  },
  { headline_font: 'Hammersmith One',
    body_font: 'Source Sans Pro',
    category_id: Category.where(name: 'casual').first.id,
    slider1: 3,
    slider2: 4,
    slider3: 2
  },
  { headline_font: 'Hammersmith One',
    body_font: 'Molengo',
    category_id: Category.where(name: 'casual').first.id,
    slider1: 4,
    slider2: 4,
    slider3: 2
  }
])
