# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Category.delete_all
Category.create([
  {name: 'formal'},
  {name: 'casual'}
])
## Each entry seperated by brackets, all entries must be followed by comma
## except for the last.
Pair.delete_all
Pair.create([
  { headline_font: 'Abril Fatface',
    body_font: 'Open Sans',
    category_id: Category.where(name: 'formal').first.id,
    playful: 0,
    light: 1,
    modern: 1
  },
  { headline_font: 'Plaster',
    body_font: 'Ubuntu',
    category_id: Category.where(name: 'casual').first.id,
    playful: 1,
    light: 0,
    modern: 1
  },
  { headline_font: 'Oleo Script',
    body_font: 'Open Sans',
    category_id: Category.where(name: 'casual').first.id,
    playful: 1,
    light: 0,
    modern: 1
  },
  { headline_font: 'Prata',
    body_font: 'Vollkorn',
    category_id: Category.where(name: 'formal').first.id,
    playful: 0,
    light: 1,
    modern: 0
  },
  { headline_font: 'Marko One',
    body_font: 'Roboto Slab',
    category_id: Category.where(name: 'casual').first.id,
    playful: 1,
    light: 0,
    modern: 1
  },
  { headline_font: 'Racing Sans One',
    body_font: 'Ubuntu',
    category_id: Category.where(name: 'casual').first.id,
    playful: 1,
    light: 0,
    modern: 1
  },
  { headline_font: 'Yeseva One',
    body_font: 'Old Standard TT',
    category_id: Category.where(name: 'formal').first.id,
    playful: 0,
    light: 0,
    modern: 0
  },
  { headline_font: 'Poller One',
    body_font: 'Roboto Slab',
    category_id: Category.where(name: 'casual').first.id,
    playful: 1,
    light: 0,
    modern: 1
  },
  { headline_font: 'Roboto Slab',
    body_font: 'Open Sans',
    category_id: Category.where(name: 'formal').first.id,
    playful: 0,
    light: 1,
    modern: 1
  },
  { headline_font: 'Londrine Solid',
    body_font: 'Vollkorn',
    category_id: Category.where(name: 'casual').first.id,
    playful: 1,
    light: 0,
    modern: 1
  },
  { headline_font: 'Days One',
    body_font: 'Open Sans',
    category_id: Category.where(name: 'casual').first.id,
    playful: 0,
    light: 0,
    modern: 1
  },
  { headline_font: 'Acme',
    body_font: 'Old Standard TT',
    category_id: Category.where(name: 'formal').first.id,
    playful: 1,
    light: 0,
    modern: 0
  },
  { headline_font: 'Dosis',
    body_font: 'Ubuntu',
    category_id: Category.where(name: 'casual').first.id,
    playful: 1,
    light: 1,
    modern: 1
  },
  { headline_font: 'Holtwood One SC',
    body_font: 'Vollkorn',
    category_id: Category.where(name: 'casual').first.id,
    playful: 1,
    light: 0,
    modern: 1
  },
  { headline_font: 'Lily Script One',
    body_font: 'Old Standard TT',
    category_id: Category.where(name: 'casual').first.id,
    playful: 1,
    light: 0,
    modern: 1
  },
  { headline_font: 'Sail',
    body_font: 'Old Standard TT',
    category_id: Category.where(name: 'formal').first.id,
    playful: 1,
    light: 1,
    modern: 0
  },
  { headline_font: 'Sorts Mill Goudy',
    body_font: 'Vollkorn',
    category_id: Category.where(name: 'formal').first.id,
    playful: 0,
    light: 1,
    modern: 0
  },
  { headline_font: 'Boogaloo',
    body_font: 'Open Sans',
    category_id: Category.where(name: 'casual').first.id,
    playful: 1,
    light: 0,
    modern: 1
  },
  { headline_font: 'Lobster',
    body_font: 'Vollkorn',
    category_id: Category.where(name: 'formal').first.id,
    playful: 1,
    light: 0,
    modern: 0
  },
  { headline_font: 'Monoton',
    body_font: 'Open Sans',
    category_id: Category.where(name: 'casual').first.id,
    playful: 1,
    light: 0,
    modern: 1
  },
  { headline_font: 'Quando',
    body_font: 'Vollkorn',
    category_id: Category.where(name: 'formal').first.id,
    playful: 1,
    light: 1,
    modern: 0
  },
  { headline_font: 'Lemon',
    body_font: 'Open Sans',
    category_id: Category.where(name: 'casual').first.id,
    playful: 1,
    light: 0,
    modern: 1
  },
  { headline_font: 'Patua One',
    body_font: 'Ubuntu',
    category_id: Category.where(name: 'casual').first.id,
    playful: 0,
    light: 0,
    modern: 1
  },
  { headline_font: 'Alegreya SC',
    body_font: 'Vollkorn',
    category_id: Category.where(name: 'formal').first.id,
    playful: 0,
    light: 1,
    modern: 0
  },
  { headline_font: 'Corben',
    body_font: 'Vollkorn',
    category_id: Category.where(name: 'formal').first.id,
    playful: 0,
    light: 1,
    modern: 0
  },
  { headline_font: 'Salsa',
    body_font: 'Vollkorn',
    category_id: Category.where(name: 'formal').first.id,
    playful: 0,
    light: 0,
    modern: 0
  },
  { headline_font: 'Dancing Script',
    body_font: 'Vollkorn',
    category_id: Category.where(name: 'casual').first.id,
    playful: 1,
    light: 1,
    modern: 0
  },
  { headline_font: 'Bowlby One',
    body_font: 'Vollkorn',
    category_id: Category.where(name: 'formal').first.id,
    playful: 1,
    light: 0,
    modern: 1
  },
  { headline_font: 'Cambo',
    body_font: 'Open Sans',
    category_id: Category.where(name: 'formal').first.id,
    playful: 0,
    light: 1,
    modern: 1
  },
  { headline_font: 'Montserrat',
    body_font: 'Ubuntu',
    category_id: Category.where(name: 'casual').first.id,
    playful: 0,
    light: 0,
    modern: 1
  },
  { headline_font: 'Imprima',
    body_font: 'Old Standard TT',
    category_id: Category.where(name: 'formal').first.id,
    playful: 0,
    light: 1,
    modern: 0
  },
  { headline_font: 'Vidaloka',
    body_font: 'Vollkorn',
    category_id: Category.where(name: 'formal').first.id,
    playful: 1,
    light: 0,
    modern: 0
  },
  { headline_font: 'Baunmans',
    body_font: 'Ubuntu',
    category_id: Category.where(name: 'casual').first.id,
    playful: 1,
    light: 0,
    modern: 1
  },
  { headline_font: 'Signika Negative',
    body_font: 'Vollkorn',
    category_id: Category.where(name: 'formal').first.id,
    playful: 0,
    light: 0,
    modern: 0
  },
  { headline_font: 'Yanone Kaffeesatz',
    body_font: 'Ubuntu',
    category_id: Category.where(name: 'casual').first.id,
    playful: 1,
    light: 0,
    modern: 1
  },
  { headline_font: 'Sansita One',
    body_font: 'Vollkorn',
    category_id: Category.where(name: 'casual').first.id,
    playful: 1,
    light: 0,
    modern: 0
  },
  { headline_font: 'Bitter',
    body_font: 'Open Sans',
    category_id: Category.where(name: 'formal').first.id,
    playful: 0,
    light: 0,
    modern: 1
  },
  { headline_font: 'Bree Serif',
    body_font: 'Roboto Slab',
    category_id: Category.where(name: 'formal').first.id,
    playful: 1,
    light: 0,
    modern: 1
  },
  { headline_font: 'Paytone One',
    body_font: 'Roboto Slab',
    category_id: Category.where(name: 'casual').first.id,
    playful: 1,
    light: 0,
    modern: 1
  },
  { headline_font: 'Belgrano',
    body_font: 'Open Sans',
    category_id: Category.where(name: 'formal').first.id,
    playful: 0,
    light: 1,
    modern: 1
  },
  { headline_font: 'Petit Formal Script',
    body_font: 'Old Standard TT',
    category_id: Category.where(name: 'casual').first.id,
    playful: 1,
    light: 1,
    modern: 0
  },
  { headline_font: 'Bangers',
    body_font: 'Open Sans',
    category_id: Category.where(name: 'casual').first.id,
    playful: 1,
    light: 0,
    modern: 1
  },
  { headline_font: 'Great Vibes',
    body_font: 'Old Standard TT',
    category_id: Category.where(name: 'formal').first.id,
    playful: 0,
    light: 1,
    modern: 0
  },
  { headline_font: 'Gravitas One',
    body_font: 'Old Standard TT',
    category_id: Category.where(name: 'formal').first.id,
    playful: 0,
    light: 0,
    modern: 0
  },
  { headline_font: 'Convergence',
    body_font: 'Roboto Slab',
    category_id: Category.where(name: 'formal').first.id,
    playful: 1,
    light: 0,
    modern: 1
  },
  { headline_font: 'Cantala One',
    body_font: 'Vollkorn',
    category_id: Category.where(name: 'formal').first.id,
    playful: 0,
    light: 0,
    modern: 0
  },
  { headline_font: 'Cutive Mono',
    body_font: 'Ubuntu',
    category_id: Category.where(name: 'formal').first.id,
    playful: 0,
    light: 1,
    modern: 1
  },
  { headline_font: 'Jockey One',
    body_font: 'Ubuntu',
    category_id: Category.where(name: 'casual').first.id,
    playful: 1,
    light: 0,
    modern: 1
  },
  { headline_font: 'Ultra',
    body_font: 'Open Sans',
    category_id: Category.where(name: 'formal').first.id,
    playful: 1,
    light: 0,
    modern: 1
  },
  { headline_font: 'Limelight',
    body_font: 'Vollkorn',
    category_id: Category.where(name: 'formal').first.id,
    playful: 0,
    light: 0,
    modern: 1
  },
  { headline_font: 'Lato',
    body_font: 'Open Sans',
    category_id: Category.where(name: 'formal').first.id,
    playful: 0,
    light: 1,
    modern: 1
  },
  { headline_font: 'Hammersmith One',
    body_font: 'Open Sans',
    category_id: Category.where(name: 'formal').first.id,
    playful: 0,
    light: 0,
    modern: 1
  },
  { headline_font: 'Playfair Display',
    body_font: 'Old Standard TT',
    category_id: Category.where(name: 'formal').first.id,
    playful: 0,
    light: 1,
    modern: 0
  },
  { headline_font: 'Oswald',
    body_font: 'Ubuntu',
    category_id: Category.where(name: 'casual').first.id,
    playful: 1,
    light: 0,
    modern: 1
  },
  { headline_font: 'Rokkitt',
    body_font: 'Open Sans',
    category_id: Category.where(name: 'formal').first.id,
    playful: 0,
    light: 0,
    modern: 1
  },
  { headline_font: 'Domine',
    body_font: 'Old Standard TT',
    category_id: Category.where(name: 'formal').first.id,
    playful: 1,
    light: 0,
    modern: 0
  },
  { headline_font: 'Roboto',
    body_font: 'Open Sans',
    category_id: Category.where(name: 'formal').first.id,
    playful: 0,
    light: 0,
    modern: 1
  },
  { headline_font: 'Jura',
    body_font: 'Ubuntu',
    category_id: Category.where(name: 'casual').first.id,
    playful: 1,
    light: 1,
    modern: 1
  },
  { headline_font: 'Amaranth',
    body_font: 'Vollkorn',
    category_id: Category.where(name: 'casual').first.id,
    playful: 0,
    light: 0,
    modern: 0
  },
  { headline_font: 'Poly',
    body_font: 'Open Sans',
    category_id: Category.where(name: 'formal').first.id,
    playful: 0,
    light: 0,
    modern: 0
  },
  { headline_font: 'Signika',
    body_font: 'Open Sans',
    category_id: Category.where(name: 'casual').first.id,
    playful: 0,
    light: 1,
    modern: 1
  },
  { headline_font: 'Italianno',
    body_font: 'Old Standard TT',
    category_id: Category.where(name: 'formal').first.id,
    playful: 0,
    light: 1,
    modern: 0
  },
  { headline_font: 'Bevan',
    body_font: 'Roboto Slab',
    category_id: Category.where(name: 'formal').first.id,
    playful: 1,
    light: 0,
    modern: 1
  },
  { headline_font: 'Kreon',
    body_font: 'Open Sans',
    category_id: Category.where(name: 'formal').first.id,
    playful: 1,
    light: 0,
    modern: 1
  },
  { headline_font: 'Coda Caption',
    body_font: 'Ubuntu',
    category_id: Category.where(name: 'casual').first.id,
    playful: 1,
    light: 0,
    modern: 1
  },
  { headline_font: 'Merriweather',
    body_font: 'Open Sans',
    category_id: Category.where(name: 'formal').first.id,
    playful: 1,
    light: 1,
    modern: 1
  }])
